# Generated by Django 3.0.2 on 2020-01-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guides',
            new_name='Guide',
        ),
        migrations.RenameModel(
            old_name='GuideOrders',
            new_name='GuideOrder',
        ),
    ]
