# Generated by Django 3.0.2 on 2020-01-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20200119_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
