# Generated by Django 3.0.2 on 2020-01-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guide_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
