# Generated by Django 3.0.2 on 2020-04-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_guideorder_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.CharField(max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GuideTable', to='guides.Guide')),
            ],
            options={
                'verbose_name': 'Guide Price Table',
                'verbose_name_plural': 'Guide Price Tables',
            },
        ),
    ]
