# Generated by Django 3.0.2 on 2020-04-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_guidepricetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guidepricetable',
            name='desc_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guidepricetable',
            name='desc_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
