# Generated by Django 3.0.2 on 2020-04-20 05:58

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_auto_20200418_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='content_ru',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
