# Generated by Django 3.0.2 on 2020-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0010_guide_content_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guidepricetable',
            name='desc_bg',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
