# Generated by Django 3.0.2 on 2020-01-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200111_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
