# Generated by Django 3.0.2 on 2020-01-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20200112_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
