# Generated by Django 3.0.2 on 2020-01-18 00:11

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tourcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
