# Generated by Django 3.0.2 on 2020-01-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Tour Order',
                'verbose_name_plural': 'Tour Orders',
            },
        ),
    ]
