# Generated by Django 3.0.2 on 2020-02-16 09:35

from django.db import migrations, models
import django.db.models.deletion
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_toursliderimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourorders',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='toursliderimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.upload_image_path),
        ),
        migrations.CreateModel(
            name='TourPriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.CharField(max_length=50)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TourTable', to='tours.Tour')),
            ],
            options={
                'verbose_name': 'Tour Price Table',
                'verbose_name_plural': 'Tour Price Tables',
            },
        ),
        migrations.CreateModel(
            name='TourComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tour', to='tours.Tour')),
            ],
            options={
                'verbose_name': 'Tour Comment',
                'verbose_name_plural': 'Tour Comments',
            },
        ),
    ]
