# Generated by Django 3.0.2 on 2020-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_auto_20200216_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='city_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpricetable',
            name='desc_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tourpricetable',
            name='desc_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
