# Generated by Django 3.0.2 on 2020-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_tour_content_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_es',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpricetable',
            name='desc_es',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
