# Generated by Django 3.0.2 on 2020-06-09 09:27

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_tour_content_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='content_bg',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
