# Generated by Django 3.0.2 on 2020-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_tour_content_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_bg',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpricetable',
            name='desc_bg',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
