# Generated by Django 3.0.2 on 2020-02-16 09:37

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', froala_editor.fields.FroalaField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='visa/e_visa')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='ContactFormInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Form Information',
                'verbose_name_plural': 'Contact Form Information',
            },
        ),
        migrations.CreateModel(
            name='EvisaOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('passport_scans', models.FileField(upload_to='visa/e_visa_order/passport_scans')),
                ('document_scans', models.FileField(upload_to='visa/e_visa_order/document_scans/')),
            ],
            options={
                'verbose_name': 'E-Visa Order',
                'verbose_name_plural': 'E-Visa Orders',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('phone_num', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=200)),
                ('company_address', models.CharField(max_length=200)),
                ('facebook_link', models.CharField(max_length=200)),
                ('skype_link', models.CharField(max_length=200)),
                ('vk_link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Website settings',
                'verbose_name_plural': 'Website settings',
            },
        ),
        migrations.CreateModel(
            name='VisaServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='E-visa to Azerbaijan', max_length=200)),
                ('content', froala_editor.fields.FroalaField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='visa/e_visa')),
            ],
            options={
                'verbose_name': 'Visa Services',
                'verbose_name_plural': 'Visa Services',
            },
        ),
    ]
