# Generated by Django 3.0.2 on 2020-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotravel_app', '0003_auto_20200420_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_address_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visaservices',
            name='name_es',
            field=models.CharField(default='E-visa to Azerbaijan', max_length=200, null=True),
        ),
    ]
