# Generated by Django 3.0.2 on 2020-07-13 00:07

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geotravel_app', '0007_auto_20200609_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookiePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', froala_editor.fields.FroalaField()),
                ('content_ru', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('content_es', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('content_bg', froala_editor.fields.FroalaField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cookie Policy',
                'verbose_name_plural': 'Cookie Policies',
            },
        ),
    ]
