# Generated by Django 3.0.2 on 2020-02-16 09:35

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import transport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_url', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Car Rent Order',
                'verbose_name_plural': 'Car Rent Orders',
            },
        ),
        migrations.CreateModel(
            name='TransformCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to=transport.models.upload_image_path)),
                ('passenger', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Transform Car',
                'verbose_name_plural': 'Transform Cars',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('passenger', models.IntegerField(default=4)),
                ('year', models.CharField(max_length=4)),
                ('body_style', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to=transport.models.upload_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.VehicleCategory')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.CharField(max_length=400)),
                ('to', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passenger_number_one_way', models.IntegerField()),
                ('passenger_number_two_way', models.IntegerField(blank=True, null=True)),
                ('flight_one_way', models.CharField(max_length=400)),
                ('flight_two_way', models.CharField(blank=True, max_length=400, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=80)),
                ('plate_info', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date_arrival', models.DateField()),
                ('date_arrival_time', models.TimeField()),
                ('date_arrival_two_way', models.DateField()),
                ('date_arrival_time_two_way', models.TimeField()),
                ('transform_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.TransformCars')),
            ],
            options={
                'verbose_name': 'Transfer Order',
                'verbose_name_plural': 'Transfer Orders',
            },
        ),
    ]
