# Generated by Django 3.0.2 on 2020-02-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferOrder',
        ),
    ]
