# Generated by Django 3.0.2 on 2020-02-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_delete_transferorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.CharField(max_length=400)),
                ('to', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passenger_number_one_way', models.IntegerField()),
                ('passenger_number_two_way', models.IntegerField(blank=True, null=True)),
                ('flight_one_way', models.CharField(max_length=400)),
                ('flight_two_way', models.CharField(blank=True, max_length=400, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=80)),
                ('plate_info', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_arrival', models.DateField()),
                ('date_arrival_time', models.TimeField()),
                ('date_arrival_two_way', models.DateField()),
                ('date_arrival_time_two_way', models.TimeField()),
                ('transform_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.TransformCars')),
            ],
            options={
                'verbose_name': 'Transfer Order',
                'verbose_name_plural': 'Transfer Orders',
            },
        ),
    ]
