# Generated by Django 3.0.2 on 2020-02-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transferorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferorder',
            name='date_arrival_time_two_way',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='date_arrival_two_way',
            field=models.DateField(blank=True, null=True),
        ),
    ]
