# Generated by Django 3.0.2 on 2020-04-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transferpricetable_transferstaticpage_transferstaticpageorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferpricetable',
            name='desc_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferpricetable',
            name='desc_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferstaticpage',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transferstaticpage',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transformcars',
            name='category_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transformcars',
            name='category_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transformcars',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transformcars',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='body_style_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='body_style_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='transmission_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='transmission_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
