# Generated by Django 3.0.2 on 2020-04-20 05:58

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20200419_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferstaticpage',
            name='content_ru',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='content_ru',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
