# Generated by Django 3.0.2 on 2020-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20200420_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferpricetable',
            name='desc_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferstaticpage',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transformcars',
            name='category_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transformcars',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='body_style_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='transmission_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
