# Generated by Django 3.0.2 on 2020-05-03 23:45

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_auto_20200420_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferstaticpage',
            name='content_es',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='content_es',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
