# Generated by Django 3.0.2 on 2020-06-09 09:27

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20200504_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferstaticpage',
            name='content_bg',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='content_bg',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
