# Generated by Django 3.0.2 on 2020-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20200609_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferpricetable',
            name='desc_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferstaticpage',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transformcars',
            name='category_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transformcars',
            name='name_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='name_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='body_style_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='name_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='transmission_bg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
